### ISSUE TITLE
代码生成了,但是控制台报错字符串索引越界

### ISSUE THREAD

**Issue by sussenn** [shenkunlin/code-template#1]
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.substring(String.java:1963)
	at com.itheima.code.util.StringUtils.firstUpper(StringUtils.java:16)
	at com.itheima.code.build.TemplateBuilder.builder(TemplateBuilder.java:180)
	at com.itheima.CodeApplication.main(CodeApplication.java:14)

Process finished with exit code 1

**Comment by 3022982925** [comment]
import javafx.scene.control.Tab;你导入这个包了吗

**Comment by Q2035** [comment]
> 
> 
> import javafx.scene.control.Tab;你导入这个包了吗

这个可以删除，我这边试了试问题出在获取数据库内的表名上，换一个获取方式就能生成了（我提了PR，有需要可以看看https://github.com/shenkunlin/code-template/pull/3   ）。

**Comment by jiayusheng123** [comment]
我的为什么报这个错误代码也没有生成

**Comment by jiayusheng123** [comment]
求解

**Comment by Q2035** [comment]
> 
> 
> 求解

之前提过PR，拉取我的代码试试看。
